# Generated by Django 2.0 on 2017-12-12 15:23

from django.db import migrations, models
import ukuApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement', models.Field(verbose_name=ukuApp.models.Agreement)),
                ('title_text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100)),
                ('desc_date', models.TextField(max_length=1024)),
            ],
        ),
    ]
