# Generated by Django 2.0 on 2017-12-15 15:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100, verbose_name='活动名称')),
                ('desc_text', models.TextField(default='This is the default description', max_length=1024, verbose_name='活动详情')),
                ('start_date', models.DateField(default=datetime.date.today, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='开始日期')),
                ('end_date', models.DateField(default=datetime.date.today, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', verbose_name='结束日期')),
                ('status', models.BooleanField(default=True, verbose_name='是否有效')),
                ('fields_to_display', models.CharField(choices=[('租用', '姓名|电话|地址|学校|学生证号|产品'), ('会员', '姓名|电话|备注')], default='Membership', max_length=12, verbose_name='显示字段')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100, verbose_name='标题')),
                ('desc_text', models.TextField(default='This is the default description', max_length=1024, verbose_name='描述')),
            ],
            options={
                'verbose_name': '协议',
                'verbose_name_plural': '协议',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(max_length=100, verbose_name='标题')),
                ('desc_text', models.TextField(default='This is the default description', max_length=1024, verbose_name='描述')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
            },
        ),
        migrations.CreateModel(
            name='SignupInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phoneNum', models.DecimalField(decimal_places=0, max_digits=11, verbose_name='Phone Number')),
                ('address', models.TextField(default='This is the default address', max_length=1024, verbose_name='Address')),
                ('school', models.TextField(default='This is the default school', max_length=1024, verbose_name='School Name')),
                ('idNum', models.DecimalField(decimal_places=0, max_digits=30, verbose_name='ID Number')),
                ('remark', models.TextField(blank=True, max_length=1024, verbose_name='Remarks')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ukuApp.Activity')),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ukuApp.Product')),
            ],
            options={
                'verbose_name': '报名',
                'verbose_name_plural': '报名',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='agreement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ukuApp.Agreement', verbose_name='使用协议'),
        ),
        migrations.AddField(
            model_name='activity',
            name='products',
            field=models.ManyToManyField(to='ukuApp.Product', verbose_name='参与的产品'),
        ),
    ]
