# Generated by Django 2.0 on 2017-12-19 04:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ukuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signupinfo',
            options={'verbose_name': '报名名单', 'verbose_name_plural': '报名名单'},
        ),
        migrations.AddField(
            model_name='signupinfo',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='signupinfo',
            name='sex',
            field=models.CharField(choices=[('M', '男孩子'), ('F', '女孩子')], default='M', max_length=3, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='agreement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agreement', to='ukuApp.Agreement', verbose_name='使用协议'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='desc_text',
            field=models.TextField(blank=True, default='This is the default description', max_length=1024, verbose_name='活动详情'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='fields_to_display',
            field=models.CharField(choices=[('租用', '姓名|性别|电话|地址|学校|学号|产品|备注'), ('会员', '姓名|性别|电话|学校|学号|备注')], default='租用', max_length=12, verbose_name='显示字段'),
        ),
        migrations.AlterField(
            model_name='signupinfo',
            name='address',
            field=models.TextField(default='This is the default address', max_length=1024, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='signupinfo',
            name='idNum',
            field=models.TextField(default='IDNUM123', max_length=30, verbose_name='学号'),
        ),
        migrations.AlterField(
            model_name='signupinfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='signupinfo',
            name='phoneNum',
            field=models.DecimalField(decimal_places=0, max_digits=11, verbose_name='电话'),
        ),
        migrations.AlterField(
            model_name='signupinfo',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='ukuApp.Product', verbose_name='租琴型号'),
        ),
        migrations.AlterField(
            model_name='signupinfo',
            name='remark',
            field=models.TextField(blank=True, max_length=1024, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='signupinfo',
            name='school',
            field=models.TextField(default='This is the default school', max_length=100, verbose_name='学校'),
        ),
    ]
