# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ukuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fields_to_display',
            field=models.CharField(choices=[('rental', 'name|phoneNum|address|school|idNum|product'), ('member', 'name|phoneNum|remark')], default='Membership', max_length=12),
        ),
    ]
